revert using options.expiration instead of options.timeout
bringg/node-arnavmq pull request #39
Opened 2022-11-21 10:44 UTC by sergejivanoff6

Even though the change was considered as right one, it was decided to revert it as it brings breaking changes to our services

2022-11-23 11:11 UTC, shamil requested changes

2022-11-23 11:11 UTC, shamil commented on package.json
> +  "version": "0.11.0",
please bump version

2022-11-23 19:39 UTC, yosiat approved these changes

2022-11-23 19:54 UTC, sergejivanoff6 commented on src/modules/producer.js
> -          options.expiration = options.timeout;
@yosiat just to make it clear, nothing prevents from using options.expiration even if we do total rollback. If I got you right, you propose to keep the warnings but not to force people to use expiration? This is an interesting compromise that didn't come to my mind...

2022-11-25 15:47 UTC, sergejivanoff6 commented
close PR in favour of https://github.com/bringg/node-arnavmq/pull/40

2022-11-25 15:47 UTC, closed without merging