Support prefetch per queue
bringg/node-arnavmq pull request #44
Opened 2022-12-29 06:52 UTC by hilaBringg

2022-12-29 15:52 UTC, yosiat requested changes

2022-12-29 15:52 UTC, yosiat commented on src/modules/connection.js
> +  get(queue, prefetch) {
Maybe we should accept here "options" instead of prefetch, in case we have more arguments we want to pass along

2023-01-03 14:04 UTC, ramhr requested changes

2023-01-03 19:36 UTC, hilaBringg commented on test/rpc-spec.js
> +  it('should be able to consume with custom prefetch & reply msg', () => arnavmq.consumer.consume(fixtures.queues[3], { channel: { prefetch: 2 } }, () => ({ powerRangerColor: 'Yellow' }))
'npm run lint' throw error when adding line:
`62:57  error  Block must not be padded by blank lines  padded-blocks`

2023-01-03 19:37 UTC, hilaBringg commented on src/modules/connection.js
> +    const channelOptions = getChannelOptions(options);
this function exist for 2 reasons:
1. avoid code duplication (used twice)
2. when i replace this function with `const channelOptions = options?.channel;` and run 'npm run lint' it throw error '84:36  error  Parsing error: Unexpected token .'

2023-02-01 09:30 UTC, closed without merging