Remove nodejs v16 support.
bringg/node-arnavmq pull request #94
Opened 2024-10-22 13:57 UTC by ramhr

nodejs 16 has reached end-of-life on September last year, and this month it reaches the end of it's maintenance mode as well, removing all official support.

In order to keep maintaining the package and update dependencies we reached a point where we need to stop support for it as well.

2024-10-22 13:59 UTC, shamil requested changes

2024-10-22 13:59 UTC, shamil commented on .github/workflows/ci.yml
> +        node-version: [18.x, 20.x]
please test also version 22

2024-10-23 09:53 UTC, yosiat approved these changes

2024-10-27 09:02 UTC, eylonronen approved these changes

2024-10-29 14:46 UTC, merged